-- Run this in the Supabase SQL editor to enable the quest and rumor board.
CREATE TABLE IF NOT EXISTS public.quest_board (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_type text NOT NULL CHECK (entry_type IN ('quest', 'rumor')),
  status text NOT NULL CHECK (
    (entry_type = 'quest' AND status IN ('open', 'in_progress', 'completed'))
    OR (entry_type = 'rumor' AND status IN ('unverified', 'confirmed', 'false'))
  ),
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  reward text NOT NULL DEFAULT '',
  visible_to_players boolean NOT NULL DEFAULT true,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.campaign_dashboard (
  id smallint PRIMARY KEY CHECK (id = 1),
  next_session_date date,
  next_session_notes text NOT NULL DEFAULT '',
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL
);

INSERT INTO public.campaign_dashboard (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.quest_board ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.quest_board TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.quest_board_id_seq TO authenticated;
ALTER TABLE public.campaign_dashboard ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE ON TABLE public.campaign_dashboard TO authenticated;

DROP POLICY IF EXISTS campaign_dashboard_select ON public.campaign_dashboard;
CREATE POLICY campaign_dashboard_select
  ON public.campaign_dashboard FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS campaign_dashboard_insert ON public.campaign_dashboard;
CREATE POLICY campaign_dashboard_insert
  ON public.campaign_dashboard FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = (SELECT auth.uid())
        AND profiles.role = 'dm'
    )
  );

DROP POLICY IF EXISTS campaign_dashboard_update ON public.campaign_dashboard;
CREATE POLICY campaign_dashboard_update
  ON public.campaign_dashboard FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = (SELECT auth.uid())
        AND profiles.role = 'dm'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = (SELECT auth.uid())
        AND profiles.role = 'dm'
    )
  );

DROP POLICY IF EXISTS quest_board_select ON public.quest_board;
CREATE POLICY quest_board_select
  ON public.quest_board FOR SELECT TO authenticated
  USING (
    visible_to_players
    OR EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = (SELECT auth.uid())
        AND profiles.role = 'dm'
    )
  );

DROP POLICY IF EXISTS quest_board_insert ON public.quest_board;
CREATE POLICY quest_board_insert
  ON public.quest_board FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = (SELECT auth.uid())
        AND profiles.role = 'dm'
    )
  );

DROP POLICY IF EXISTS quest_board_update ON public.quest_board;
CREATE POLICY quest_board_update
  ON public.quest_board FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = (SELECT auth.uid())
        AND profiles.role = 'dm'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = (SELECT auth.uid())
        AND profiles.role = 'dm'
    )
  );

DROP POLICY IF EXISTS quest_board_delete ON public.quest_board;
CREATE POLICY quest_board_delete
  ON public.quest_board FOR DELETE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = (SELECT auth.uid())
        AND profiles.role = 'dm'
    )
  );
