create table if not exists public.password_reset_requests (
  id bigint generated by default as identity primary key,
  username text not null,
  email text not null,
  status text not null default 'pending' check (status in ('pending', 'handled')),
  created_at timestamptz not null default now(),
  handled_by uuid references auth.users(id),
  handled_at timestamptz
);

alter table public.password_reset_requests enable row level security;

create policy "Authenticated users can create reset requests"
on public.password_reset_requests for insert
to authenticated
with check (true);

create policy "DMs can read reset requests"
on public.password_reset_requests for select
to authenticated
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role = 'dm'
  )
);

create policy "DMs can handle reset requests"
on public.password_reset_requests for update
to authenticated
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role = 'dm'
  )
)
with check (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role = 'dm'
  )
);
